### PR TITLE
[app-emulation/packer] Version bump to 1.2.3

### PR DESCRIPTION
**Pull request by hlein**
Upstream has moved CONTRIBUTING.md to a subdir, otherwise trivial.

PR ready for review

### CODE REVIEW

**Comment by hlein** [comment]
Note, I believe the Travis CI failure is because there are errors elsewhere in the current tree.  `repoman fix -d` fails for me with similar `dependency.bad` errors on a fresh clone of go-overlay with zero changes.

**Comment by bpinto** [comment]
Why are we installing CONTRIBUTING as a doc? Shouldn't we remove it from the ebuild?

**Comment by ganto** [comment]
> Why are we installing CONTRIBUTING as a doc? Shouldn't we remove it from the ebuild?

What's wrong with that? I've also always regarded this as part of doc.

**Comment by hlein** [comment]
I don't care either way, but since CONTRIBUTING was already being installed, I just fixed its path so it still works in the bumped version.

**Comment by bpinto** [comment]
`CONTRIBUTING` is a github specific file, it's even stored in a `.github` folder. A normal user shouldn't care about docs from developers.

**Comment by hlein** [comment]
Closing this and will issue a new PR for packer 1.2.5.

**Pull request closed without merging**
