### PR TITLE
[app-emulation/packer] new ebuild packer-0.8.6

### PR DESCRIPTION
**Pull request by ganto**
Hi

I created a new ebuild for Hashicorp's [packer](https://packer.io) utility.

First thing to mention, I'm very impressed by your `golang-single` eclass. Works like a charm. 

Still I couldn't use `golang-single_src_compile`, as upstream requires some fancy output binary naming. I also use a custom `src_test` function, as otherwise it would recompile every binary again. Still not sure if this is intended, as I saw this behaviour with the upstream Gentoo golang-eclasses too. I'm pretty new with Golang, so you may have some hints for me.

If you want to have a look at the ebuild... I think it's ready for review.

Cheers, ganto

### CODE REVIEW

**Comment by Dr-Terrible** [comment]
> Hi
> I created a new ebuild for Hashicorp's packer utility.

Hi @ganto, and thank you very much for your ebuild contribution; `packer` was indeed among my wish list of packages to add to the overlay. So your contribution is really welcome :D

> First thing to mention, I'm very impressed by your golang-single eclass. Works like a charm.

Keep in mind that the upstream Gentoo golang-\* eclasses tend to install everything systemwide (inside your GOROOT), especially some golang libraries. That approach is _really bad_, and is not really a recommended behaviour by the Go project: https://golang.org/doc/code.html (see paragraph about _workspaces_). Chances are that those libraries installed by Gentoo eclasses are going to compromise your personal GOPATH, or even worse.

What I do with my eclass is to be fully compliant with the upstream specs about golang workspaces, nothing else; that is why my eclass _works like a charm_, while Gentoo golang eclasses don't ;)

> Still I couldn't use golang-single_src_compile, as upstream requires some fancy output binary naming

It's a common requirement among golang packages, and obviously the `golang-single.eclass` has helpers for such features too. So far, I didn't inspect the source code of packer, but I'm pretty confident that you can achieve the same results by using _golang-single_src_compile()_ and avoid entirely the gox dependency.

> I also use a custom src_test function, as otherwise it would recompile every binary again. Still not sure if this is intended, as I saw this behaviour with the upstream Gentoo golang-eclasses too.

Unfortunately, that is a feature of Go itself. It is intended by design, since the go toolchain is trying to build a new binary (generally called $package.test) and then run it; so the go toolchain is not really rebuilding the main package, but a new binary ($package.test), hence the _compilation output_ that you noticed in the terminal and tried to avoid, or optimize.

However, your `src_test()` phase boils down to exactly what my eclass does for every ebuild: invoking `go test ./...`, so I'm pretty sure it is redundant (unless there is something tricky going on within packer source code).

Apart from that, your ebuild is amazing. You have done a really good job despite my sparse documentation. Here are some other tips:
1. you should check the source code of packer for `go:generate` annotations (a grep is usually enough); if there are annotations, you should add `GOLANG_PKG_USE_GENERATE=1` to the ebuild, and eventually all the dependencies required by go:generate.
2. most probably packer has a built-in documentation in html, or some man pages; you should include them too and add the USE flag 'doc'; this part could be tricky, especially the html generation; if you have problems, leave it out and I'll fix it later.
3. since you're adding an ebuild for a stable release you can safely add stable KEYWORDS.
4. this is not really mandatory, but I need to know with which version of Go you have tested the package (Go1.4, or Go1.5?).

While you're fixing up your PR, I'm going to inspect packer build scripts and see if we can use `golang-single_src_compile()` and `golang-single_src_test()`.

**Comment by Dr-Terrible** [comment]
Other tips:
1. you should add a `metadata.xml` file; for a reference see https://github.com/Dr-Terrible/go-overlay/blob/master/net-misc/syncthing/metadata.xml or https://github.com/Dr-Terrible/go-overlay/blob/master/www-apps/hugo/metadata.xml; if you're willing to maintain future versions of the same package, feel free to add your personal informations.
2. you should not depend on `dev-go/go-tools`; instead you should use my version of the same package: `dev-util/go-tools` (it is an updated version and it doesn't pollute your GOROOT with golang toolchain garbage);
3. packer offers bash-zsh autocompletion, you should add them too, coupled with the proper USE flags;

As I suspected, using gox was unnecessary. You can safely compile the package with `golang-single_src_compile()`, both of them produce the same binary:

``` sh
# package built with golang-single_src_compile()
-rwxr-xr-x 1 root root 7735440 Jan 14 12:05 /usr/bin/packer

# package built with gox:
-rwxr-xr-x 1 root root 7735440 Jan 14 12:18 /usr/bin/packer
```

All you need to do to trigger the same behaviour of gox is to entirely remove your custom `src_compile()` and add this helper: `GOLANG_PKG_IS_MULTIPLE=1`. The `golang-single` eclass will take care of all the rest ;)

The same goes for `src_test()`. The _compilation output_ that you saw previously — during the test phase — was a side effect of the missing `GOLANG_PKG_IS_MULTIPLE=1`; without it, the eclass builds only the main package (which is /usr/bin/packer), ignoring all the rest, so during the test phase the go toolchain was forced to (re)build all the missing utils to properly execute all the unit tests. `GOLANG_PKG_IS_MULTIPLE=1` fixes all of that, without adding extra complexity to the ebuild.

Finally, the src_install should be like this:

``` sh
src_install() {
    golang-single_src_install

    # prefixing all the binaries
    for pkg in "${ED}"/usr/bin/*; do
        [[ "${PN}" == ${pkg##*/} ]] && continue
        mv "${pkg}" "${ED}"/usr/bin/${PN}-${pkg##*/} || die
    done
}
```

**Comment by ganto** [comment]
Thanks a lot for your comprehensive review. I'm going to address the points that you mentioned. Still a few comments:

> Keep in mind that the upstream Gentoo golang-\* eclasses tend to install everything systemwide (inside your GOROOT), especially some golang libraries. That approach is really bad, and is not really a recommended behaviour by the Go project.

I see. Before I noticed your eclass, I was trying to create a packer ebuild with the upstream eclasses which forced me to create a separate ebuild for every dependency. After a few days I finally achieved my goal, but only after patching here and there and cumbersome try and error and many workarounds. After updating from Go 1.4 to 1.5 in the course of development I then saw some confusing failure cases when trying to build everything from scratch which made me look for a better way. The elegance of your solution is super nice. With your eclass it only took me a few hours to complete the initial version.

> GOLANG_PKG_IS_MULTIPLE=1 fixes all of that, without adding extra complexity to the ebuild.

I was definitely missing that. Thanks for hinting me. 

> most probably packer has a built-in documentation in html, or some man pages; you should include them too and add the USE flag 'doc'

I think the repository even includes the complete website. I was looking at it for my initial version but if I remember correctly it needs some fancy tools to be built. Will have a look at it again.

> this is not really mandatory, but I need to know with which version of Go you have tested the package (Go1.4, or Go1.5?)

I was testing with `dev-lang/go-1.5.1-r1` from the official Gentoo portage. I think one of the dependencies failed to build with go-1.4, which made me switch. Will definitely have a look at it again.

This makes me think of another question I was still unsure about. Is there any rule/best-practise in how to choose the commit hashes of the dependencies? In this case, `packer-0.8.6` is already quite old (August 2015), but still I choose the most recent commits for the dependencies whenever possible. I thought that they might include some bugfixes not available in the original version. There are two exceptions however, the AWS and Google Cloud API golang projects had some API changes in the meantime which caused the packer build to fail. So I was picking a commit which is from around the date of the original packer release. However, this is hard to identify by simply looking at the ebuild itself.

**Comment by ganto** [comment]
I tried to use the `golang-single_src_compile`/`golang-single_src_install` functions with `GOLANG_PKG_IS_MULTIPLE=1`, however, I end up with the following installation error:

```
 >>> Install packer-0.8.6 into /var/tmp/portage/app-emulation/packer-0.8.6/image/ category app-emulation
 * go install -ldflags '' -tags '' -v -x -p 1
WORK=/var/tmp/portage/app-emulation/packer-0.8.6/temp/go-build241257130
net
mkdir -p $WORK/net/_obj/
mkdir -p $WORK/
cd /usr/lib/go/src/net
/usr/lib/go/pkg/tool/linux_amd64/compile -o $WORK/net.a -trimpath $WORK -p net -buildid b1148872ea8d8a847674bc006d6c449ae8e06d21 -D _/usr/lib/go/src/net -I $WORK -pack ./addrselect.go ./cgo_stub.go ./conf.go ./dial.go ./dnsclient.go ./dns
client_unix.go ./dnsconfig_unix.go ./dnsmsg.go ./fd_mutex.go ./fd_poll_runtime.go ./fd_posix.go ./fd_unix.go ./file.go ./file_unix.go ./hook.go ./hook_cloexec.go ./hook_unix.go ./hosts.go ./interface.go ./interface_linux.go ./ip.go ./ipra
wsock.go ./iprawsock_posix.go ./ipsock.go ./ipsock_posix.go ./lookup.go ./lookup_unix.go ./mac.go ./net.go ./nss.go ./parse.go ./pipe.go ./port.go ./port_unix.go ./sendfile_linux.go ./sock_cloexec.go ./sock_linux.go ./sock_posix.go ./sock
opt_linux.go ./sockopt_posix.go ./sockoptip_linux.go ./sockoptip_posix.go ./tcpsock.go ./tcpsock_posix.go ./tcpsockopt_posix.go ./tcpsockopt_unix.go ./udpsock.go ./udpsock_posix.go ./unixsock.go ./unixsock_posix.go
mkdir -p /usr/lib/go/pkg/linux_amd64/
cp $WORK/net.a /usr/lib/go/pkg/linux_amd64/net.a
go install net: open /usr/lib/go/pkg/linux_amd64/net.a: permission denied
[...]
 * ERROR: app-emulation/packer-0.8.6::go-overlay failed (install phase):
```

It seems that it tries to install some build artefacts into the live file system. I'm not so experienced with golang to understand what is going on here. Can you help me?

**Comment by Dr-Terrible** [comment]
> Before I noticed your eclass, I was trying to create a packer ebuild with the upstream eclasses **which forced me to create a separate ebuild for every dependency**. After a few days I finally achieved my goal, but only after patching here and there and cumbersome try and error and many workarounds. **After updating from Go 1.4 to 1.5 in the course of development I then saw some confusing failure cases** when trying to build everything from scratch [...]

I got bitten by the same issues too; several times. That is why I created this overlay: to overcome the never ending frustration of dealing with Gentoo golang-\* eclasses. :D

What is absurd is that the Go lang specs clearly state that dependencies should never be installed in GOROOT. Instead, they should be _vendored_ inside a GOPATH because everything is statically compiled whitin your GOPATH. This specific aspect has been made explicit in Go1.5 (with env variable [GO15VENDOREXPERIMENT](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit#!)), and would be mandatory for Go1.6+.

> I think the repository even includes the complete website. I was looking at it for my initial version but if I remember correctly it needs some fancy tools to be built. Will have a look at it again.

You are right. It requires [middleman](http://middlemanapp.com) to build the documentation. In turn, Middleman requires several ruby dependencies, and both Middleman and the deps are not available in Portage (or any other overlay). Creating new ebuilds for them will be quite cumbersome, so feel free to skip this part.

> I was testing with dev-lang/go-1.5.1-r1 from the official Gentoo portage. I think one of the dependencies failed to build with go-1.4, which made me switch.

Indeed, there was a bug in my eclass that affected several packages; the bug has been fixed just recently: #10. `dev-util/go-tools` should be fixed now. In case, open a bug report if you find issues.

> Is there any rule/best-practise in how to choose the commit hashes of the dependencies? In this case, packer-0.8.6 is already quite old (August 2015), but still I choose the most recent commits for the dependencies whenever possible. I thought that they might include some bugfixes not available in the original version. There are two exceptions however, the AWS and Google Cloud API golang projects had some API changes in the meantime which caused the packer build to fail. So I was picking a commit which is from around the date of the original packer release. However, this is hard to identify by simply looking at the ebuild itself. 

There aren't best practises when picking up golang dependencies. Generally speaking, most of the time the deps are vendored inside the source code (or there is a *.json manifest enlisting all of them and their commit hashes); when the deps are not vendored, as a rule of thumb, I generally use the most recent version of all the dependencies. I pick up old commit hashes only when the source code doesn't compile (due to specific APIs signatures) or requires a version of a library specifically.

**Comment by Dr-Terrible** [comment]
> I tried to use the `golang-single_src_compile`/`golang-single_src_install` functions with `GOLANG_PKG_IS_MULTIPLE=1`, however, I end up with the following installation error: [..] It seems that it tries to install some build artefacts into the live file system. I'm not so experienced with golang to understand what is going on here. Can you help me?

Sure. Can you paste your ebuild somewhere so I can test it? 

However, I'm pretty sure the infamous upstream Gentoo golang-\* eclass have bitten you in the ass, again. I provide a solution in #15 ;)

**Comment by ganto** [comment]
Thanks a lot. [Here](https://gist.github.com/ganto/29f6907bde9faf5ec465) it is.

**Comment by Dr-Terrible** [comment]
Unfortunately, I'm not able to reproduce the aforementioned issue :(

[Here](https://gist.github.com/Dr-Terrible/b6a578641ccd928fbff3) the output of packer-0.8.6 built with Go1.5. [Here](https://gist.github.com/Dr-Terrible/b2c58f6501ce85dcfe3e) the output of packer-0.8.6 built with Go1.4.

As you can see, both of them compile fine, and all the tests pass successfully.

I'm still convinced that you have stumbled on #15. I have updated that issue report with new instructions for better addressing these kind of compilation errors. Try to remove `dev-go/go-net`, and make sure that the file `/usr/lib/go/pkg/linux_amd64/net.a` is effectively purged from your filesystem. Most probably that file is still present in your system even after the removal of `dev-go/go-net`.

**Comment by ganto** [comment]
I'm glad to hear that it works. You were right, I have a hell lot of files under `/usr/lib/{go,go-gentoo,go-1.4}` which are not owned by any package although as far as I remember I always used eclasses to do go stuff. I'll clean up my system then try to reproduce your success and finish the remaining issues. Thanks a lot for your help.

**Comment by ganto** [comment]
I'm not sure how long I'll be interested in maintaining this ebuild, as it's currently doing what I need. If you're fine to take over feel free to do so. I didn't dare to assign you as a maintainer without asking you first.

**Comment by Dr-Terrible** [comment]
> I have a hell lot of files under /usr/lib/{go,go-gentoo,go-1.4} which are not owned by any package

I got stuck in a similar situation some time ago, when I upgraded from Go1.4.2 to Go1.5.1. To restore my GOROOT environment to a sane state, I had to remove all the golang libraries installed by emerge (you can use this command: `qlist -I -C dev-go/ | xargs emerge -C`), then both `dev-lang/go` and `dev-lang/go-bootstrap`, and finally manually erase `/usr/lib/go/{doc,include,lib,pkg,src}`. That was the only way to be sure to nuke all the old and unused *.a file archive.

I suspect that emerge got confused somewhere along the line during the upgrade of Go1.4.2 to Go1.5.1 and left tons of orphaned files for no good reasons. Most probably, it's a portage bug. An annoying one, for sure.

> Thanks a lot for your help.

You're welcome.

**Comment by Dr-Terrible** [comment]
> I'm not sure how long I'll be interested in maintaining this ebuild, as it's currently doing what I need. If you're fine to take over feel free to do so. I didn't dare to assign you as a maintainer without asking you first.

Well, maintaining an already created ebuild is quite trivial (you just need to update some deps here and there and then test the package, nothing else), so if you're not willing to assign yourself then add my credentials. I'll take care of future versions.

As a side note, if you need new ebuilds for packages written in golang, I can give you access to this repository and make you a collaborator with commit privileges. That way your future PRs will be a lot more faster to commit. You're more than welcome. ;)

**Comment by ganto** [comment]
> As a side note, if you need new ebuilds for packages written in golang, I can give you access to this repository and make you a collaborator with commit privileges. That way your future PRs will be a lot more faster to commit. 

Thanks a lot for your offer. I think for now it's not the worst idea if you first have a look over my ebuilds before adding them to your overlay.

If you're interested I would soon send you another PR for [hub](https://hub.github.com/) (maybe you already saw it at ganto@ffd6307). At the moment there are still some tests failing where I think they shouldn't. I'm still trying to figure out what's the matter there.

**Comment by Dr-Terrible** [comment]
> I think for now it's not the worst idea if you first have a look over my ebuilds before adding them to your overlay.

Sure.

> If you're interested I would soon send you another PR for hub (maybe you already saw it at ganto@ffd6307).

There is already an ebuild for hub v2.2.2 in this overlay: https://github.com/Dr-Terrible/go-overlay/blob/master/dev-util/hub/hub-2.2.2.ebuild. Maybe we can condense both of them into a better and improved ebuild.

I see, my ebuild uses a different category (`dev-util/hub`) than the official one in portage (`dev-vcs/hub`). Upstream must have changed the category without me noticing it. Well, it can be easily fixed, it's not a big deal.

> At the moment there are still some tests failing where I think they shouldn't. I'm still trying to figure out what's the matter there.

Sometimes, tests fail due to the inner sandbox of Portage. Try to run them as: `FEATURES="test -sandbox -sandbox-network" emerge -1av category/mypackage`. If the tests don't fail any more then just add a message in `src_test()` to warn the user about the issue, like I did for https://github.com/Dr-Terrible/go-overlay/blob/master/www-apps/hugo/hugo-0.16_pre20160104.ebuild

**Comment by ganto** [comment]
Is there still anything you want me to change? Or should I just squash the commits then merge?

**Comment by Dr-Terrible** [comment]
Thank you, @ganto. Looks good to me. Merge it :+1:

**Comment by ganto** [comment]
Merged with #24

**Pull request closed without merging**
